chore(build): refactor build scripts

diff --git a/build/publish b/build/publish
--- a/build/publish
+++ b/build/publish
@@ -4,39 +4,36 @@ DN=$(dirname "$0")
 BN=$(basename "$0")
 
 PROJ_HOME=$(cd "${DN}/.."; pwd)
+BUILD_SH_HOME="${PROJ_HOME}/build/sh"
+
 . "${DN}/sh/lib.sh"
 
+#---------------------------------------------------------
+[ -f "${DN}/config" ] || die "config '${DN}/config' not found"
+. "${DN}/config"
 
 #---------------------------------------------------------
 
-echo 'Are you shure you want to publish to npm registry (yes|no)?'
+echo 'Are you sure you want to publish to npm registry (yes|no)?'
 read answer
 if [ "${answer}" != "yes" ]; then
   exit 0
 fi
 
-pushd "${PROJ_HOME}/dist/@angular-dynaform/core" &>/dev/null || \
-    die "directory '${PROJ_HOME}/dist/@angular-dynaform/core' not found"
-  npm publish --access=public || \
-      die "failed to publish 'core'"
-popd &>/dev/null
 
-pushd "${PROJ_HOME}/dist/@angular-dynaform/basic" &>/dev/null || \
-    die "directory '${PROJ_HOME}/dist/@angular-dynaform/basic' not found"
-  npm publish --access=public || \
-      die "failed to publish 'basic'"
-popd &>/dev/null
+pushd "${PROJ_HOME}" &>/dev/null        || die "failed to cwd '${PROJ_HOME}'"
 
-pushd "${PROJ_HOME}/dist/@angular-dynaform/material" &>/dev/null || \
-    die "directory '${PROJ_HOME}/dist/@angular-dynaform/material' not found"
-  npm publish --access=public || \
-      die "failed to publish 'material'"
-popd &>/dev/null
+  for file in "${PKG_JSONS_DIST[@]}"; do
+    dir=$(dirname "${file}")
 
-pushd "${PROJ_HOME}/dist/@angular-dynaform/nativescript" &>/dev/null || \
-    die "directory '${PROJ_HOME}/dist/@angular-dynaform/nativescript' not found"
-  npm publish --access=public --tag next || \
-      die "failed to publish 'nativescript'"
+    pushd "${dir}" &>/dev/null || \
+        die "directory 'dir' not found"
+      npm publish --access=public || \
+          die "failed to publish in '${dir}'"
+    popd &>/dev/null
+
+  done
+
 popd &>/dev/null
 
 
diff --git a/build/version-bump b/build/version-bump
--- a/build/version-bump
+++ b/build/version-bump
@@ -9,15 +9,8 @@ BUILD_SH_HOME="${PROJ_HOME}/build/sh"
 . "${DN}/sh/lib.sh"
 
 #---------------------------------------------------------
-
-PKGJSON=(
-  package.json
-  package-lock.json
-  projects/angular-dynaform/core/package.json
-  projects/angular-dynaform/basic/package.json
-  projects/angular-dynaform/material/package.json
-  projects/angular-dynaform/nativescript/package.json
-)
+[ -f "${DN}/config" ] || die "config '${DN}/config' not found"
+. "${DN}/config"
 
 #---------------------------------------------------------
 if [ $# -ne 1 ]; then
@@ -26,10 +19,20 @@ if [ $# -ne 1 ]; then
 fi
 VER=$1
 
+PKGS=()
+PKGS+=( "${PKG_JSONS[@]}" )
+PKGS+=( "${PKG_JSON_LOCKS[@]}" )
+
 pushd "${PROJ_HOME}" &>/dev/null        || die "failed to cwd '${PROJ_HOME}'"
 
-  for file in "${PKGJSON[@]}"; do
-    ${BUILD_SH_HOME}/tsrun version-bump.ts "${file}" "${VER}"
+  for file in "${PKGS[@]}"; do
+    if [[ "$file" == */nativescript/* ]]; then
+      ${BUILD_SH_HOME}/tsrun version-bump.ts "${file}" "${VER}-alpha.0"
+    else
+      ${BUILD_SH_HOME}/tsrun version-bump.ts "${file}" "${VER}"
+    fi
   done
 
 popd &>/dev/null
+echo
+"${DN}/post-install"
