chore(package): show output of npm install on travis

diff --git a/build/travis_before b/build/travis_before
--- a/build/travis_before
+++ b/build/travis_before
@@ -11,14 +11,14 @@ PROJ_HOME=$(cd "${DN}/.."; pwd)
 pushd "${PROJ_HOME}" &>/dev/null        || die "failed to cwd '${PROJ_HOME}'"
 
 echo "*** install main..."
-npm install &>/dev/null                 || die "failed to install package 'root'"
+npm install                             || die "failed to install package 'root'"
 echo "*** install main: done"
 
   # --- core package
   pushd "packages/core" &>/dev/null     || die "failed to cwd 'packages/core'"
 
     echo "*** install package/core..."
-    npm install &>/dev/null             || die "failed to install package 'core'"
+    npm install                         || die "failed to install package 'core'"
     echo "*** install package/core: done"
     echo "*** build   package/core..."
     gulp rebuild --prod                 || die "failed to build package 'core'"
@@ -29,7 +29,7 @@ echo "*** install main: done"
   pushd "packages/basic" &>/dev/null    || die "failed to cwd 'packages/basic'"
 
     echo "*** install package/basic..."
-    npm install &>/dev/null             || die "failed to install package 'basic'"
+    npm install                         || die "failed to install package 'basic'"
     echo "*** install package/basic: done"
     echo "*** build   package/basic..."
     gulp rebuild --prod                 || die "failed to build package 'basic'"
@@ -41,7 +41,7 @@ echo "*** install main: done"
                                         || die "failed to cwd 'packages/basic-example'"
 
     echo "*** install package/basic-example..."
-    npm install &>/dev/null             || die "failed to install package 'basic-example'"
+    npm install                         || die "failed to install package 'basic-example'"
     echo "*** install package/basic-example: done"
     echo "*** build   package/basic-example..."
     ng build -aot                       || die "failed to build package 'basic-example'"
@@ -53,7 +53,7 @@ echo "*** install main: done"
   pushd "packages/material" &>/dev/null || die "failed to cwd 'packages/material'"
 
     echo "*** install package/material..."
-    npm install &>/dev/null             || die "failed to install package 'material'"
+    npm install                         || die "failed to install package 'material'"
     echo "*** install package/material: done"
     echo "*** build   package/material..."
     gulp rebuild --prod                 || die "failed to build package 'material'"
@@ -65,7 +65,7 @@ echo "*** install main: done"
                                         || die "failed to cwd 'packages/material-example'"
 
     echo "*** install package/material-example..."
-    npm install &>/dev/null             || die "failed to install package 'material-example'"
+    npm install                         || die "failed to install package 'material-example'"
     echo "*** install package/material-example: done"
     echo "*** build   package/material-example..."
     ng build -aot                       || die "failed to build package 'material-example'"
